name : Cow

on:
  workflow_dispatch:


jobs:
  cow:
    runs-on: ubuntu-latest
    steps:
    - name: Cow says meow
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'MEOW'
        color: 'magenta'